- name: Deploy localtraderpy to environment
  hosts: all
  tasks:

  - name: pull manually
    become_user: localtrader
    ansible.builtin.shell:
      cmd: "docker pull europe-north1-docker.pkg.dev/spacetraders-424214/localtrader/localtraderpy:{{environment_name}}"

  - name: write docker compose file
    become_user: localtrader
    ansible.builtin.template:
      src: roles/common/templates/docker-compose.yml.j2
      dest: /tmp/docker-compose.yml
      mode: '0444'

  - name: docker compose up
    become_user: localtrader
    shell: 
      cmd: docker compose up -d
      chdir: /tmp