- name: Prepare jenkins agent
  hosts: all
  become: true
  tasks:
  - name: Set authorized key taken from file
    ansible.posix.authorized_key:
      user: ian
      state: present
      key: "{{ lookup('file', 'roles/common/files/jenkins-agent.key.pub') }}"

  - name: Install java
    apt:
      pkg:
        - default-jre
      state: latest
      update_cache: true